import { Property } from '@/components/card/propertycard'
import { siteConfig } from '@/lib/site-config'

export const properties: Property[] = [
    {
        id: '1',
        pid: 'TB08419',
        title: 'Waterfront Executive Duplex',
        tagline: '5 bedrooms with private pool, BQ and direct lagoon frontage on Banana Island.',
        type: 'Duplex',
        purpose: 'for-sale',
        price: 850_000_000,
        bedrooms: 5,
        bathrooms: 6,
        parkingSpaces: 3,
        areaSqM: 720,
        neighborhood: 'Banana Island',
        address: '26 Balfour Road, Banana Island',
        images: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
        ],
        featured: true,
        description:
            'An exceptional waterfront executive duplex on prestigious Banana Island. This five-bedroom residence features a private swimming pool, self-contained guest quarters and direct lagoon frontage with uninterrupted water views. The interiors are finished to the highest international standard with premium marble, bespoke joinery and floor-to-ceiling glazing that floods the living spaces with natural light.',
        features: [
            'Private Infinity Pool',
            'Direct Lagoon Frontage',
            'Self-Contained BQ',
            'Smart Home Automation',
            'CCTV & 24/7 Security',
            'Gym & Wellness Room',
            'Double-Garage Parking',
            'Backup Generator',
            'Staff Quarters',
            'Landscaped Garden',
        ],
        titleDocument: "Governor's Consent",
        furnishing: 'Fully Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Murtala Muhammed Intl (20 km)',
            nearestMall: 'Landmark / City Mall',
            nearestHospital: 'First Cardiology Consultants',
            beachAccess: 'Onitsha Crescent Beach (10 min)',
        },
        agent: {
            name: 'Adaeze Nwosu',
            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
    {
        id: '2',
        pid: 'TB07312',
        title: 'Skyline Penthouse',
        tagline: 'Full-floor penthouse with panoramic Atlantic views and private elevator.',
        type: 'Penthouse',
        purpose: 'for-rent',
        price: 45_000_000,
        period: 'per annum',
        bedrooms: 4,
        bathrooms: 5,
        parkingSpaces: 2,
        areaSqM: 480,
        neighborhood: 'Victoria Island',
        address: '14 Akin Adesola Street, Victoria Island',
        images: [
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
        ],
        featured: true,
        description:
            'A full-floor penthouse commanding panoramic Atlantic views from the heart of Victoria Island. Accessible via a private elevator, this exceptional residence offers expansive open-plan living, floor-to-ceiling windows, a designer kitchen and a wraparound terrace perfect for entertaining. A rare combination of privacy, prestige and breathtaking skyline vistas.',
        features: [
            'Private Elevator',
            'Panoramic Ocean Views',
            'Wraparound Terrace',
            'Designer Kitchen',
            'Concierge Service',
            'Smart Home Automation',
            'Secure Valet Parking',
            'Backup Power',
        ],
        titleDocument: 'Deed of Assignment',
        furnishing: 'Fully Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Murtala Muhammed Intl (24 km)',
            nearestMall: 'E-Centre / Palms Mall',
            nearestHospital: 'Lagoon Hospitals',
            beachAccess: 'Oniru Beach (8 min)',
        },
        agent: {
            name: 'Tunde Bakare',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
    {
        id: '3',
        pid: 'TB06807',
        title: 'Serviced Luxury Shortlet',
        tagline: 'Fully serviced 3-bed shortlet with concierge, gym and 24/7 security in the heart of Ibadan.',
        type: 'Shortlet',
        purpose: 'shortlet',
        price: 220_000,
        period: 'per day',
        bedrooms: 3,
        bathrooms: 4,
        parkingSpaces: 1,
        areaSqM: 310,
        neighborhood: 'Ibadan City',
        address: '7 Sango Ring Road, Ibadan',
        images: [
            'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        ],
        featured: true,
        description:
            'A fully serviced three-bedroom luxury shortlet in the heart of Ibadan. Enjoy a five-star standard of living with daily housekeeping, a dedicated concierge, a well-equipped gym and 24/7 security. Ideal for executives, business travellers and families seeking a refined, worry-free stay.',
        features: [
            'Daily Housekeeping',
            'Dedicated Concierge',
            'Fully Equipped Gym',
            '24/7 Security',
            'High-Speed Fibre Internet',
            'Smart TV & Streaming',
            'Fully Fitted Kitchen',
            'Backup Power & Water',
        ],
        titleDocument: "Governor's Consent",
        furnishing: 'Fully Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Ibadan Airport (16 km)',
            nearestMall: 'Cocoa Mall',
            nearestHospital: 'University College Hospital',
            beachAccess: 'None — Inland City',
        },
        agent: {
            name: 'Chiamaka Obi',
            avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
    {
        id: '4',
        pid: 'TB09233',
        title: 'Ikoyi Garden Residence',
        tagline: 'Gated 4-bedroom apartment with lush courtyard, en-suite staff quarters and 24/7 security.',
        type: 'Apartment',
        purpose: 'for-rent',
        price: 28_000_000,
        period: 'per annum',
        bedrooms: 4,
        bathrooms: 5,
        parkingSpaces: 2,
        areaSqM: 420,
        neighborhood: 'Ikoyi',
        address: '3 Bourdillon Road, Ikoyi',
        images: [
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
        ],
        description:
            'Set within an exclusive gated community, this four-bedroom garden residence blends serene courtyard living with secure, low-density surroundings. The home features generous en-suite bedrooms, integrated staff quarters and round-the-clock security, all within easy reach of Ikoyi\u2019s finest addresses and amenities.',
        features: [
            'Gated Community',
            'Lush Private Courtyard',
            'En-Suite Staff Quarters',
            '24/7 Armed Security',
            'Integrated Kitchen',
            'Private Study',
            'Visitor Parking',
            'Backup Generator',
        ],
        titleDocument: "Governor's Consent",
        furnishing: 'Semi-Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Murtala Muhammed Intl (22 km)',
            nearestMall: 'Ikoyi Square / Mega Plaza',
            nearestHospital: 'St. Nicholas Hospital',
            beachAccess: 'Oniru Beach (15 min)',
        },
        agent: {
            name: 'Simisola Adeleke',
            avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
    {
        id: '5',
        pid: 'TB06154',
        title: 'Lekki Corporate Shortlet',
        tagline: 'Serviced 2-bed corporate shortlet ideal for executives, with high-speed internet and gym.',
        type: 'Shortlet',
        purpose: 'shortlet',
        price: 180_000,
        period: 'per day',
        bedrooms: 2,
        bathrooms: 3,
        parkingSpaces: 1,
        areaSqM: 240,
        neighborhood: 'Lekki Phase 1',
        address: '12 Admiralty Way, Lekki Phase 1',
        images: [
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
        ],
        description:
            'A serviced two-bedroom corporate shortlet crafted for the modern executive. Located on the vibrant Admiralty Way, it delivers high-speed fibre internet, a well-appointed fitness centre and quiet, secure surroundings — perfect for business stays, relocations and extended trips. More than a room, it is a productive home away from home.',
        features: [
            'High-Speed Fibre Internet',
            'Executive Workspace',
            'Fitness Centre',
            '24/7 Security & CCTV',
            'Daily Housekeeping',
            'Smart TV & Soundbar',
            'Fully Fitted Kitchen',
            'Backup Power & Water',
        ],
        titleDocument: "Governor's Consent",
        furnishing: 'Fully Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Murtala Muhammed Intl (28 km)',
            nearestMall: 'The Palms / Circle Mall',
            nearestHospital: 'Reddington Hospital',
            beachAccess: 'Elegushi Beach (6 min)',
        },
        agent: {
            name: 'Emeka Nwosu',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
    {
        id: '6',
        pid: 'TB07809',
        title: 'Abuja Hillside Villa',
        tagline: 'Contemporary 5-bed villa with scenic Maitama views, smart security and landscaped gardens.',
        type: 'Villa',
        purpose: 'for-sale',
        price: 310_000_000,
        bedrooms: 5,
        bathrooms: 6,
        parkingSpaces: 3,
        areaSqM: 650,
        neighborhood: 'Maitama',
        city: 'Abuja',
        address: '18 Alvan Ikoku Way, Maitama, Abuja',
        images: [
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
        ],
        description:
            'A contemporary five-bedroom villa in the serene hills of Maitama, Abuja. Set on landscaped gardens with smart security and expansive entertaining spaces, this residence offers the ultimate in modern Abuja living. Scenic district views, premium finishes and thoughtfully designed interiors make it a standout offering.',
        features: [
            'Scenic Maitama Views',
            'Smart Security System',
            'Landscaped Gardens',
            'Cinema Room',
            'Wine Cellar',
            'Inverter & Solar Backup',
            'Triple Garage',
            'Staff Quarters',
        ],
        titleDocument: "Certificate of Occupancy",
        furnishing: 'Fully Furnished',
        neighborhoodInfo: {
            nearestAirport: 'Nnamdi Azikiwe Intl (40 km)',
            nearestMall: 'Jabi Lake Mall',
            nearestHospital: 'Cedarcrest Hospital',
            beachAccess: 'None — Inland City',
        },
        agent: {
            name: 'Adaeze Nwosu',
            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
            whatsapp: siteConfig.whatsappNumber,
            phone: siteConfig.officePhone,
        },
    },
]
